using System.Collections.Generic;
using System.ComponentModel;

namespace CyberHeaven.Services
{
    public class LocalizationService : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        private string _currentLanguage = "ru"; 

        private readonly Dictionary<string, Dictionary<string, string>> _dictionaries = new()
        {
            ["en"] = new()
            {
                ["AuthorizationTitle"] = "Authorization",
                ["RegistrationTitle"] = "Registration",
                ["LoginButton"] = "Login",
                ["RegisterButton"] = "Register",
                ["RegisterPrompt"] = "Don't have an account? Register",
                ["LoginPrompt"] = "Already have an account? Login",
                ["ReviewButton"] = "Reviews",
                ["BookingButton"] = "Booking",
                ["MainButton"] = "Main",
                ["SalesButton"] = "Sales/Packages",
                ["TournamentsButton"] = "About us",
                ["AdminButton"] = "Admin",
                ["MainTitle1"] = "CYBER",
                ["MainTitle2"] = "HEAVEN",
                ["BookNowButton"] = "BOOK NOW",
                ["Promo1Title"] = "PROMOTION",
                ["Promo1Subtitle"] = "For first booking",
                ["Promo1Discount"] = "20% discount",
                ["Promo2Title"] = "PACKAGE",
                ["Promo2Subtitle"] = "When choosing 'Night' package",
                ["Promo2Discount"] = "15% discount",
                ["PromoHoverText"] = "GO TO PROMOTIONS SECTION",

                ["FirstNameLabel"] = "First name (2-50 chars, no digits)",
                ["LastNameLabel"] = "Last name (2-50 chars, no digits)",
                ["PhoneLabel"] = "Phone number (7 digits)",
                ["EmailLabel"] = "Email",
                ["UsernameLabel"] = "Username (2-20 chars)",
                ["PasswordLabel"] = "Password (6+ chars, letters and numbers)",
                ["ConfirmPasswordLabel"] = "Confirm password",

                ["FirstNameError"] = "Invalid first name",
                ["LastNameError"] = "Invalid last name",
                ["PhoneError"] = "Invalid phone number",
                ["EmailError"] = "Invalid email",
                ["UsernameError"] = "Invalid username",
                ["PasswordError"] = "Invalid password",
                ["ConfirmPasswordError"] = "Passwords don't match",
                ["PasswordMismatchError"] = "Passwords don't match",
                ["PasswordTooShortError"] = "Password must be at least 6 characters",
                ["InvalidEmailError"] = "Invalid email format",

                ["RegistrationSuccessful"] = "Registration successful! You can now login",
                ["GoToLoginButton"] = "Go to login",
                ["SalesTitle"] = "PROMOTIONS AND PACKAGES",
                ["CreatePromoTitle"] = "Create new promotion",
                ["EditPromoTitle"] = "Edit promotion",
                ["DeletePromoTitle"] = "Delete promotion",
                ["PromoNameLabel"] = "Promotion name:",
                ["DescriptionLabel"] = "Description:",
                ["PromoCodeLabel"] = "Promo code:",
                ["DiscountLabel"] = "Discount percentage:",
                ["SelectPromoLabel"] = "Select promotion:",
                ["SelectPromoToDeleteLabel"] = "Select promotion to delete:",
                ["CreateButton"] = "Create",
                ["SaveButton"] = "Save",
                ["DeleteButton"] = "Delete",
                ["CancelButton"] = "Cancel",
                ["CreatePromoButton"] = "Create promotion",
                ["EditPromoButton"] = "Edit promotion",
                ["DeletePromoButton"] = "Delete promotion",
                ["ClickToCopy"] = "CLICK TO COPY PROMO CODE",
                ["NewNameLabel"] = "New name:",
                ["NewDescriptionLabel"] = "New description:",
                ["NewCodeLabel"] = "New code:",
                ["NewDiscountLabel"] = "New discount percentage:",

                ["FirstNameLengthError"] = "First name must be between 2-50 characters",
                ["FirstNameNoDigitsError"] = "First name cannot contain digits and chars",
                ["LastNameLengthError"] = "Last name must be between 2-50 characters",
                ["LastNameNoDigitsError"] = "Last name cannot contain digits and chars",
                ["PhoneFormatError"] = "Phone number must be 7 digits",
                ["EmailRequiredError"] = "Email is required",
                ["UsernameRequiredError"] = "Username is required",
                ["UsernameLengthError"] = "Username must be between 2-20 characters",
                ["UsernameExistsError"] = "Username already exists",
                ["PasswordRequiredError"] = "Password is required",
                ["PasswordComplexityError"] = "Password must contain uppercase, lowercase and numbers",
                ["ConfirmPasswordRequiredError"] = "Please confirm your password",
                ["NotFoundUser"] = "Not found User",
                ["Uncorrectusernameorpassword"] = "Uncorrect username or password",
                ["AuthError"] = "Auth Error",

                ["UserProfileTitle"] = "User Profile",
                ["BackButtonTooltip"] = "Back to main",
                ["EditProfileButton"] = "Edit Profile",
                ["MyBookingsButton"] = "My Bookings",
                ["SettingsButton"] = "Settings",
                ["LogoutButton"] = "Logout",
                ["MyBookingsHeader"] = "My Bookings",
                ["CancelBookingButton"] = "Cancel",
                ["SettingsHeader"] = "Settings",
                ["ChangePasswordHeader"] = "Change Password",
                ["CurrentPasswordPlaceholder"] = "Current Password",
                ["NewPasswordPlaceholder"] = "New Password",
                ["ConfirmPasswordPlaceholder"] = "Confirm Password",
                ["ChangePasswordButton"] = "Change Password",
                ["StatusConfirmed"] = "Confirmed",
                ["StatusPending"] = "Pending",
                ["StatusCancelled"] = "Cancelled",
                ["BookingDateLabel"] = "Date:",
                ["BookingTimeLabel"] = "Time:",
                ["BookingStatusLabel"] = "Status:",
                ["BookingComputerLabel"] = "Computer:",
                ["AdminPanelTitle"] = "Admin Panel",
                ["LogoutButton"] = "Log out",
                ["ExitAppButton"] = "Exit application",
                ["BookingRequestsTab"] = "Booking requests",
                ["PendingRequests"] = "Pending approval",
                ["ActiveBookings"] = "Active bookings",
                ["ApproveButton"] = "Approve",
                ["RejectButton"] = "Reject",
                ["CompleteButton"] = "Complete",
                ["CancelButton"] = "Cancel",
                ["UserManagementTab"] = "User management",
                ["BlockedStatus"] = "Blocked",
                ["ActiveStatus"] = "Active",
                ["ChangeAvatarButton"] = "Change avatar",
                ["EditButton"] = "Edit",
                ["BlockUserButton"] = "Block user",
                ["UnblockUserButton"] = "Unblock user",
                ["SaveButton"] = "Save",
                ["CancelEditButton"] = "Cancel",
                ["UsernameLabel"] = "Username",
                ["EmailLabel"] = "Email",
                ["PhoneLabel"] = "Phone",
                ["StatusLabel"] = "Status",
                ["RussianLanguage"] = "Russian",
                ["EnglishLanguage"] = "English",
                ["ToggleThemeTooltip"] = "Toggle theme",
                ["Time"] = "Время: ",
                ["BookingTitle"] = "Booking",
                ["PlaceCategoryLabel"] = "Place category",
                ["SpecificPlaceLabel"] = "Specific place",
                ["BookingDateLabel"] = "Booking date",
                ["StartTimeLabel"] = "Start time",
                ["EndTimeLabel"] = "End time",
                ["PromoCodeLabel"] = "Promo code (if any)",
                ["TotalPriceLabel"] = "Total amount",
                ["ConfirmBookingButton"] = "CONFIRM BOOKING",
                ["SortByCategoryButton"] = "By category",
                ["BlockPlaceButton"] = "Block",
                ["UnblockPlaceButton"] = "Unblock",
                ["AddPlaceButton"] = "Add place",
                ["RemovePlaceButton"] = "Remove place",
                ["SaveChangesButton"] = "Save changes",
                ["BookedStatus"] = "BOOKED",
                ["BlockedStatus"] = "BLOCKED",
                ["PoSale1"] = " by Cost (↓)",
                ["PoSale2"] = "by  Cost (↑)",
                ["LeaveReviewPrompt"] = "Leave your review",
                ["SubmitReviewButton"] = "Submit review",
                ["LoginToReviewPrompt"] = "You need to login to leave a review",
                ["ReviewsTitle"] = "Reviews",
                ["ReplyButton"] = "Reply",
                ["DeleteButton"] = "Delete",
                ["AdminResponseTitle"] = "Admin response:",
                ["SortNewestFirst"] = "Newest first",
                ["SortOldestFirst"] = "Oldest first",
                ["SortPositiveFirst"] = "Positive first",
                ["SortNegativeFirst"] = "Negative first",
                ["DateLabel"] = "Date",
                ["AdminResponsePlaceholder"] = "Type admin response here",
                ["ReviewCommentPlaceholder"] = "Type your review here"

            },
            ["ru"] = new()
            {
                ["AuthorizationTitle"] = "Авторизация",
                ["RegistrationTitle"] = "Регистрация",
                ["LoginButton"] = "Войти",
                ["RegisterButton"] = "Зарегистрироваться",
                ["RegisterPrompt"] = "Ещё нет аккаунта? Зарегистрируйтесь",
                ["LoginPrompt"] = "Уже зарегистрированы? Войдите в систему",
                ["ReviewButton"] = "Отзывы",
                ["BookingButton"] = "Бронь",
                ["SalesButton"] = "Акции/Пакеты",
                ["TournamentsButton"] = "О нас",
                ["AdminButton"] = "Админ",
                ["MainTitle1"] = "CYBER",
                ["MainTitle2"] = "HEAVEN",
                ["MainButton"] = "Главная",
                ["BookNowButton"] = "ЗАБРОНИРОВАТЬ",
                ["Promo1Title"] = "АКЦИЯ",
                ["Promo1Subtitle"] = "При первом бронировании",
                ["Promo1Discount"] = "скидка 20%",
                ["Promo2Title"] = "ПАКЕТ",
                ["Promo2Subtitle"] = "При выборе пакета 'ночной'",
                ["Promo2Discount"] = "действует скидка 15%",
                ["PromoHoverText"] = "ПЕРЕЙТИ В РАЗДЕЛ АКЦИИ",
                ["FirstNameLabel"] = "Имя (2-50 символов, без цифр)",
                ["LastNameLabel"] = "Фамилия (2-50 символов, без цифр)",
                ["PhoneLabel"] = "Номер телефона (7 цифр)",
                ["EmailLabel"] = "Email",
                ["UsernameLabel"] = "Логин (2-20 символов)",
                ["PasswordLabel"] = "Пароль (6+ символов, буквы и цифры)",
                ["ConfirmPasswordLabel"] = "Подтверждение пароля",

                ["FirstNameError"] = "Некорректное имя",
                ["LastNameError"] = "Некорректная фамилия",
                ["PhoneError"] = "Некорректный номер телефона",
                ["EmailError"] = "Некорректный email",
                ["UsernameError"] = "Некорректный логин",
                ["PasswordError"] = "Некорректный пароль",
                ["ConfirmPasswordError"] = "Пароли не совпадают",
                ["PasswordMismatchError"] = "Пароли не совпадают",
                ["PasswordTooShortError"] = "Пароль должен быть не менее 6 символов",
                ["InvalidEmailError"] = "Неверный формат email",

                ["RegistrationSuccessful"] = "Регистрация успешна! Теперь вы можете войти",
                ["GoToLoginButton"] = "Перейти к авторизации",
                ["SalesTitle"] = "АКЦИИ И ПАКЕТЫ",
                ["CreatePromoTitle"] = "Создание новой акции",
                ["EditPromoTitle"] = "Редактирование акции",
                ["DeletePromoTitle"] = "Удаление акции",

                // Формы
                ["PromoNameLabel"] = "Название акции:",
                ["DescriptionLabel"] = "Описание:",
                ["PromoCodeLabel"] = "Код акции:",
                ["DiscountLabel"] = "Акционный процент:",
                ["SelectPromoLabel"] = "Выберите акцию:",
                ["SelectPromoToDeleteLabel"] = "Выберите акцию для удаления:",

                // Кнопки
                ["CreateButton"] = "Создать",
                ["SaveButton"] = "Сохранить",
                ["DeleteButton"] = "Удалить",
                ["CancelButton"] = "Отмена",
                ["CreatePromoButton"] = "Создать акцию",
                ["EditPromoButton"] = "Редактировать акцию",
                ["DeletePromoButton"] = "Удалить акцию",

                // Сообщения
                ["ClickToCopy"] = "НАЖМИТЕ, ЧТОБЫ СКОПИРОВАТЬ АКЦИОННЫЙ КОД",
                ["NewNameLabel"] = "Новое название:",
                ["NewDescriptionLabel"] = "Новое описание:",
                ["NewCodeLabel"] = "Новый код:",
                ["NewDiscountLabel"] = "Новый акционный процент:",

                ["FirstNameLengthError"] = "Имя должно быть от 2 до 50 символов",
                ["FirstNameNoDigitsError"] = "Имя не должно содержать цифры и символы",
                ["LastNameLengthError"] = "Фамилия должна быть от 2 до 50 символов",
                ["LastNameNoDigitsError"] = "Фамилия не должна содержать цифры и символы",
                ["PhoneFormatError"] = "Номер телефона должен содержать 7 цифр",
                ["EmailRequiredError"] = "Email обязателен",
                ["UsernameRequiredError"] = "Логин обязателен",
                ["UsernameLengthError"] = "Логин должен быть от 2 до 20 символов",
                ["UsernameExistsError"] = "Такой логин уже существует",
                ["PasswordRequiredError"] = "Пароль обязателен",
                ["PasswordComplexityError"] = "Пароль должен содержать заглавные, строчные буквы и цифры",
                ["ConfirmPasswordRequiredError"] = "Подтвердите пароль",
                ["NotFoundUser"] = "Пользователь не найден",
                ["Uncorrectusernameorpassword"] = "Неверный логин или пароль",
                ["AuthError"] = "Ошибка авторизации",

                ["UserProfileTitle"] = "Личный кабинет",
                ["BackButtonTooltip"] = "На главную",
                ["EditProfileButton"] = "Редактировать профиль",
                ["MyBookingsButton"] = "Мои бронирования",
                ["SettingsButton"] = "Настройки",
                ["LogoutButton"] = "Выйти",
                ["MyBookingsHeader"] = "Мои бронирования",
                ["CancelBookingButton"] = "Отменить",
                ["SettingsHeader"] = "Настройки",
                ["ChangePasswordHeader"] = "Смена пароля",
                ["CurrentPasswordPlaceholder"] = "Текущий пароль",
                ["NewPasswordPlaceholder"] = "Новый пароль",
                ["ConfirmPasswordPlaceholder"] = "Подтвердите пароль",
                ["ChangePasswordButton"] = "Сменить пароль",
                ["StatusConfirmed"] = "Подтверждено",
                ["StatusPending"] = "Ожидание",
                ["StatusCancelled"] = "Отменено",
                ["BookingDateLabel"] = "Дата:",
                ["BookingTimeLabel"] = "Время:",
                ["BookingStatusLabel"] = "Статус:",
                ["BookingComputerLabel"] = "Компьютер:",
                ["AdminPanelTitle"] = "Панель администратора",
                ["LogoutButton"] = "Выйти из аккаунта",
                ["ExitAppButton"] = "Выйти из приложения",
                ["BookingRequestsTab"] = "Заявки на бронирование",
                ["PendingRequests"] = "Ожидающие подтверждения",
                ["ActiveBookings"] = "Активные бронирования",
                ["ApproveButton"] = "Принять",
                ["RejectButton"] = "Отклонить",
                ["CompleteButton"] = "Завершить",
                ["CancelButton"] = "Отменить",
                ["UserManagementTab"] = "Управление пользователями",
                ["BlockedStatus"] = "Заблокирован",
                ["ActiveStatus"] = "Активен",
                ["ChangeAvatarButton"] = "Сменить аватар",
                ["EditButton"] = "Редактировать",
                ["BlockUserButton"] = "Заблокировать",
                ["UnblockUserButton"] = "Разблокировать",
                ["SaveButton"] = "Сохранить",
                ["CancelEditButton"] = "Отмена",
                ["UsernameLabel"] = "Никнейм",
                ["EmailLabel"] = "Email",
                ["PhoneLabel"] = "Телефон",
                ["StatusLabel"] = "Статус",
                ["RussianLanguage"] = "Русский",
                ["EnglishLanguage"] = "Английский",
                ["ToggleThemeTooltip"] = "Сменить тему",
                ["Time"] = "Время: ",
                ["BookingTitle"] = "Бронирование",
                ["PlaceCategoryLabel"] = "Категория места",
                ["SpecificPlaceLabel"] = "Конкретное место",
                ["BookingDateLabel"] = "Дата бронирования",
                ["StartTimeLabel"] = "Время начала",
                ["EndTimeLabel"] = "Время окончания",
                ["PromoCodeLabel"] = "Промокод (если есть)",
                ["TotalPriceLabel"] = "Итого к оплате",
                ["ConfirmBookingButton"] = "ПОДТВЕРДИТЬ БРОНЬ",
                ["SortByCategoryButton"] = "По категории",
                ["BlockPlaceButton"] = "Заблокировать",
                ["UnblockPlaceButton"] = "Разблокировать",
                ["AddPlaceButton"] = "Добавить место",
                ["RemovePlaceButton"] = "Удалить место",
                ["SaveChangesButton"] = "Сохранить изменения",
                ["BookedStatus"] = "ЗАНЯТО",
                ["BlockedStatus"] = "ЗАБЛОКИРОВАНО",
                ["PoSale1"] = "По цене (↓)" ,
                ["PoSale2"] = "По цене (↑)",
                ["LeaveReviewPrompt"] = "Оставьте свой отзыв",
                ["SubmitReviewButton"] = "оставить отзыв",
                ["LoginToReviewPrompt"] = "Для добавления отзыва необходимо войти в систему",
                ["ReviewsTitle"] = "Отзывы",
                ["ReplyButton"] = "Ответить",
                ["DeleteButton"] = "Удалить",
                ["AdminResponseTitle"] = "Ответ администратора:",
                ["SortNewestFirst"] = "Сначала новые",
                ["SortOldestFirst"] = "Сначала старые",
                ["SortPositiveFirst"] = "Сначала положительные",
                ["SortNegativeFirst"] = "Сначала отрицательные",
                ["DateLabel"] = "Дата",
                ["AdminResponsePlaceholder"] = "Введите ответ администратора",
                ["ReviewCommentPlaceholder"] = "Введите ваш отзыв"
            }
        };

        public string this[string key]
        {
            get
            {
                if (_dictionaries.TryGetValue(_currentLanguage, out var langDict))
                {
                    if (langDict.TryGetValue(key, out var value))
                    {
                        return value;
                    }
                    return $"#[{key} not found]#"; // Запасной вариант для отсутствующих ключей
                }
                return $"#[{_currentLanguage} language not found]#";
            }
        }

        public void SetLanguage(string languageCode)
        {
            if (_dictionaries.ContainsKey(languageCode))// Проверяем наличие языка в словаре
            {
                _currentLanguage = languageCode;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null));
            }
            else
            {
                // Можно добавить логирование ошибки здесь
                System.Diagnostics.Debug.WriteLine($"Language {languageCode} not found!");
            }
        }
    }
}